version: 1.0.{build}
environment:
  access_token:
    secure: 21m76jAVvcu7oACAHFnfCBltcwon+r5ZI3avfRmrNFAqJMn6RfLXwpBhPcJ617tD
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: nuget restore -DisableParallelProcessing src\SIPSorcery.sln
build:
  project: src\SIPSorcery.sln
  publish_nuget: false
  verbosity: quiet
#test:
#  categories:
#    except:
#    - IPv6
#    - Integration
on_success:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            git config --global credential.helper store
            Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
            git config --global user.email "aaron@sipsorcery.com"
            git config --global user.name "Aaron Clauson"
            git fetch
            git checkout gh-pages -q
            git merge master
            choco install docfx -y
            & docfx docfx\docfx.json
            if ($lastexitcode -ne 0){
              throw [System.Exception] "docfx build failed with exit code $lastexitcode."
            }
            git add -A 2>&1
            git commit -am "Appveyor CI updates"
            git push origin gh-pages -q
        }