version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: nuget restore -DisableParallelProcessing src\SIPSorcery.sln
- cmd: echo Hello
build:
  project: src\SIPSorcery.sln
  publish_nuget: true
  verbosity: normal
test:
  categories:
    except:
    - Integration
after_build:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            git checkout gh-pages
            git merge master
            choco install docfx -y
            # choco install nuget.commandline -y
            # & nuget install docfx.console -Version 2.18.4 -Source https://www.myget.org/F/docfx/api/v3/index.json
            # & docfx.console.2.18.4\tools\docfx docfx.json
            & docfx docfx.json
            if ($lastexitcode -ne 0){
              throw [System.Exception] "docfx build failed with exit code $lastexitcode."
            }
            
            #git config --global credential.helper store
            #Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
            #git config --global user.email $env:op_build_user_email
            #git config --global user.name $env:op_build_user
            #git clone https://github.com/docascode/docfx-seed.git -b gh-pages origin_site -q
            #Copy-Item origin_site/.git _site -recurse
            #CD _site
            #git add -A 2>&1
            #git commit -m "CI Updates" -q
            #git push origin gh-pages -q
        }
notifications:
- provider: Email
  to:
  - aaron@sipsorcery.com
  subject: sipsorcery-core build result
  on_build_status_changed: true