version: 1.0.{build}
branches:
  except:
    - mac-ci
image: Visual Studio 2019
build_script:
- nuget restore -DisableParallelProcessing examples/sipexamples/sipexamples.sln
- msbuild examples/sipexamples/sipexamples.sln
- nuget restore -DisableParallelProcessing examples/webrtcexamples/webrtcexamples.sln
- msbuild examples/webrtcexamples/webrtcexamples.sln